import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topheader from "@/components/Topheader";
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "E Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{   
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Topheader />
        <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}
